package docsgen

import (
	"fmt"
	"io"
	"strings"

	"github.com/PrPlanIT/HASteward/src/env"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// findFlag locates a bound flag whether it lives on root's persistent flags or has been
// scoped down to a subcommand (some flags are command-specific — e.g. --method on backup
// and restore). Env-var bindings must be documented regardless of where the flag sits.
func findFlag(root *cobra.Command, name string) *pflag.Flag {
	if f := root.PersistentFlags().Lookup(name); f != nil {
		return f
	}
	for _, c := range root.Commands() {
		if f := c.Flags().Lookup(name); f != nil {
			return f
		}
		for _, gc := range c.Commands() { // one level of nesting (get/prune subgroups)
			if f := gc.Flags().Lookup(name); f != nil {
				return f
			}
		}
	}
	return nil
}

func init() {
	Register(Generator{Name: "env-reference", Title: "Environment reference", Fn: GenerateEnvReference})
}

// GenerateEnvReference renders the environment-variable reference by merging two
// authoritative sources: the env binding registry (which variable backs which flag —
// the one thing Cobra can't know) and the Cobra persistent flag itself (type, default,
// description, shorthand). Nothing is duplicated — descriptions/types/defaults live only
// on the flag. Run in a clean environment so a flag's default reflects its declared
// value, not an operator's currently-exported HASTEWARD_* variable.
func GenerateEnvReference(root *cobra.Command, w io.Writer) error {
	fmt.Fprintf(w, "<!-- generated by %s docs generate; do not edit manually -->\n\n", root.Name())

	bindings := env.Bindings()
	if len(bindings) == 0 {
		fmt.Fprintln(w, "_No environment variables are registered._")
		return nil
	}

	fmt.Fprint(w, "Every variable below sets the default for a CLI flag; an explicit flag always\n")
	fmt.Fprint(w, "overrides the environment. `HASTEWARD_`-prefixed variables are HASteward's own;\n")
	fmt.Fprint(w, "unprefixed ones (e.g. `KUBECONFIG`) are standard tools' variables it honors.\n\n")

	fmt.Fprintln(w, "| Environment Variable | Flag | Type | Default | Description |")
	fmt.Fprintln(w, "|----------------------|------|------|---------|-------------|")
	for _, b := range bindings {
		f := findFlag(root, b.Flag)
		if f == nil || f.Hidden {
			continue
		}
		def := f.DefValue
		if def == "" {
			def = "—"
		}
		flagCol := "`--" + f.Name + "`"
		if f.Shorthand != "" {
			flagCol += ", `-" + f.Shorthand + "`"
		}
		desc := strings.ReplaceAll(f.Usage, "\n", " ")
		fmt.Fprintf(w, "| `%s` | %s | `%s` | `%s` | %s |\n", b.Name(), flagCol, f.Value.Type(), def, desc)
	}
	return nil
}
